In [3]:
import numpy as np


In [4]:
List = [1,2,3,4]

In [5]:
a1 = np.array(List)
print(a1)

[1 2 3 4]


In [8]:
a7 = np.array([[10,11,12,13], [21,22,23,24]])
print(a7)

[[10 11 12 13]
 [21 22 23 24]]


In [7]:
a7[1,3]

24

In [9]:
a7[1][3]

24

In [10]:
a7

array([[10, 11, 12, 13],
       [21, 22, 23, 24]])

In [11]:
# no of axes in ndarray is called its rank


In [12]:
a7.shape

(2, 4)

In [13]:
a7.itemsize

4

In [14]:
a7.dtype


dtype('int32')

In [15]:
# what is vectorized operations in python?

In [17]:
# array  uisng list
list1 =[1,2,3,4,5]
ar1 = np.array(list1)
print(type(ar1))
print(ar1.dtype)
print(ar1.itemsize)

<class 'numpy.ndarray'>
int32
4


In [18]:
print(ar1)

[1 2 3 4 5]


In [19]:
print(ar1[0], ar1[3])

1 4


In [20]:
# create ndarray by specifing own datatype
ar3 =  np.array(list1, dtype = np.int64)
print(ar3.dtype)
print(ar3.itemsize)

int64
8


In [22]:
# array using tuple
tup1 = (2.5, 3.5 , 4.5, 6.5)
ar2 = np.array(tup1)
print(type(ar2))
print(ar2.dtype)
print(ar2.itemsize)

<class 'numpy.ndarray'>
float64
8


In [23]:
print(ar2)

[2.5 3.5 4.5 6.5]


In [24]:
print(ar2[0],  ar2[3])

2.5 6.5


In [26]:
ar4 = np.array(tup1, dtype = np.float16)
print(ar4.dtype)
print(ar4.itemsize)

float16
2


In [28]:
# creating array using dictionary
dict1 = {1:"A" , 2 :"B", 3 :"C"}
ar5 = np.array(dict1)
ar5[0]

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [30]:
# creating array using string 
ar6 = np.array("astring")
ar6[0]

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [32]:
# Creating ndarrays using fromitter()
adict = {1:"A", 2:"B", 3:"C", 4:"D", 5:"E"}
ar5 = np.fromiter(adict, dtype =np.int32)
ar5.dtype , ar5.itemsize

(dtype('int32'), 4)

In [33]:
print(ar5)

[1 2 3 4 5]


In [35]:
# creating nd array using fromiter via string datatype
astr ="thisIsGonnaFun"
ar6= np.fromiter(astr , dtype = "U2")
print(ar6)

['t' 'h' 'i' 's' 'I' 's' 'G' 'o' 'n' 'n' 'a' 'F' 'u' 'n']


In [38]:
alist = ["a","b","c","d","e"]
atup = [1.5,2.5,3.5,4.5]
lst2 = [a*2 - 3 for a in range(2,6)]
nd1 = np.fromiter(alist, dtype ="U1")
nd2 = np.fromiter(atup, dtype = "U2")
nd3 = np.fromiter(lst2, dtype = np.int16)
print(nd1)
print(nd2)
print(nd3)

['a' 'b' 'c' 'd' 'e']
['1.' '2.' '3.' '4.']
[1 3 5 7]


In [40]:
#picking a smaller set of elements from a sequence using fromiter

ar7 = np.fromiter(astr, dtype ="U1", count = 11)
ar7


array(['t', 'h', 'i', 's', 'I', 's', 'G', 'o', 'n', 'n', 'a'], dtype='<U1')

In [41]:
ar8 = np.fromiter(adict, dtype = np.int16, count = 3)
ar8

array([1, 2, 3], dtype=int16)

In [42]:
#creating ndarrays with a Numerical range using arange()
arr5 =np.arange(7)
arr5

array([0, 1, 2, 3, 4, 5, 6])

In [43]:
arr5.dtype

dtype('int32')

In [44]:
arr6 =np.arange(1,7,2, np.float32)
arr6

array([1., 3., 5.], dtype=float32)

In [45]:
#Creating arrays with a numerical range using linspace()
a1 = np.linspace(2,3,6)
a1

array([2. , 2.2, 2.4, 2.6, 2.8, 3. ])

In [46]:
a2 =np.linspace(2.5, 5, 8)
a2

array([2.5       , 2.85714286, 3.21428571, 3.57142857, 3.92857143,
       4.28571429, 4.64285714, 5.        ])