In [14]:
import numpy as np
#creating 2-dimensional Numpyarray
# 1. creating 2D array using array()
List1 =[[1,3,5],[2,4,6]]
nd2 =np.array(List1)

In [5]:
nd2

array([[1, 3, 5],
       [2, 4, 6]])

In [6]:
nd2.shape

(2, 3)

In [7]:
# creating 2D array using nested tuple
t1 =((2,4),(3,5),(6,4),(5,6))
nd3 =np.array(t1)

In [8]:
t1

((2, 4), (3, 5), (6, 4), (5, 6))

In [9]:
nd3

array([[2, 4],
       [3, 5],
       [6, 4],
       [5, 6]])

In [10]:
nd3.shape

(4, 2)

In [11]:
# Creating 2D array using arange function()
ar =np.arange(10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
ar1 = ar.reshape(5,2)
ar1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [13]:
ar2 = ar.reshape(2,5)
ar2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
ary = np.arange(8.0).reshape(2,4)
ary

array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]])

In [17]:
arr1 = np.empty( [3,2])

arr2 = np.empty([3,4], dtype = np.int8)

arr1.dtype, arr2.dtype

(dtype('float64'), dtype('int8'))

In [18]:
arr1

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
# Creating arrays filled with zeros using zeros()
arr3 = np.zeros([2,3], dtype = np.int64, order = 'F')
arr3

array([[0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [20]:
#Creating arrays filled with 1's using ones()
arr4 = np.ones([2,3], dtype = np.float32)
arr4

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [21]:
|a1 = np.eye(5)
a1

SyntaxError: invalid syntax (994089838.py, line 1)

In [22]:
a2 = np.full((2,3), 6)
a2

array([[6, 6, 6],
       [6, 6, 6]])

In [23]:
a3 = np.random.rand(3,4)
a3

array([[0.31765488, 0.89820582, 0.73972034, 0.63068973],
       [0.39528083, 0.89217795, 0.4659218 , 0.47474264],
       [0.70744234, 0.12391969, 0.12236059, 0.25700705]])

In [24]:
a4 = np.random.rand(4,5)*100
a4

array([[25.41621706, 77.92248565, 80.26304658, 21.3111017 , 96.35506264],
       [85.65090737, 43.10912618, 92.70647887, 29.56562956, 87.12190302],
       [21.33521172, 90.21970416, 38.34316774, 20.97141322, 29.61107284],
       [96.96866756,  6.14654131, 81.36889993, 23.77263782, 87.04028615]])

In [25]:
a5 = np.random.randint(5, size =(2,3))
a5

array([[0, 1, 0],
       [4, 0, 2]])

In [3]:
# Array Slicing
Ar = np.array([2,4,6,8,10,12,14,16])
Ar

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [4]:
Ar[3:7]

array([ 8, 10, 12, 14])

In [5]:
Ar[:5]

array([ 2,  4,  6,  8, 10])

In [6]:
Ar[4:]

array([10, 12, 14, 16])

In [7]:
Ar[:-1] # Sir se puchna hai

array([ 2,  4,  6,  8, 10, 12, 14])

In [8]:
Ar[:-2]

array([ 2,  4,  6,  8, 10, 12])

In [9]:
Ar[:-3]

array([ 2,  4,  6,  8, 10])

In [10]:
Ar[2:7:2]

array([ 6, 10, 14])

In [18]:
ary= np.random.randint(1,100,[4,5])
ary

array([[37, 66, 17,  3, 79],
       [55, 77, 13, 89,  3],
       [ 1, 46, 10, 90, 97],
       [97, 88,  6, 99, 14]])

In [19]:
ary[:3, 3:]

array([[ 3, 79],
       [89,  3],
       [90, 97]])

In [20]:
ary[1::2, :3]

array([[55, 77, 13],
       [97, 88,  6]])

In [21]:
ary[::3, :: 2]

array([[37, 17, 79],
       [97,  6, 14]])

In [22]:
ary[-3:-1, -5:: 2]

array([[55, 13,  3],
       [ 1, 10, 97]])

In [23]:
ary[1:3, 3:5]

array([[89,  3],
       [90, 97]])

In [24]:
ary[1:3,]

array([[55, 77, 13, 89,  3],
       [ 1, 46, 10, 90, 97]])

In [25]:
ary[: , 3: 5]

array([[ 3, 79],
       [89,  3],
       [90, 97],
       [99, 14]])

In [26]:
ary[1:4:2, 1:5: 3]

array([[77,  3],
       [88, 14]])

In [27]:
ary[2:-1,]

array([[ 1, 46, 10, 90, 97]])

In [28]:
ary[:, 1 : -2]

array([[66, 17],
       [77, 13],
       [46, 10],
       [88,  6]])

In [29]:
ary[3,]

array([97, 88,  6, 99, 14])

In [30]:
ary[:, 2]

array([17, 13, 10,  6])

In [31]:
ary[:3, :: -1]

array([[79,  3, 17, 66, 37],
       [ 3, 89, 13, 77, 55],
       [97, 90, 10, 46,  1]])

In [32]:
ary[:3, ::-2]

array([[79, 17, 37],
       [ 3, 13, 55],
       [97, 10,  1]])

In [33]:
ary[-3: -1, -4: : 2]

array([[77, 89],
       [46, 90]])

In [34]:
# Joining or Concatenating Numpy Arrays
lst1 = [1,2,3]
lst2 = [4,5,6]
lst3 =[[9,8,7],[6,5,4]]
lst4 =[[4],
      [5]]

In [35]:
sar1 = np.vstack((lst1, lst2))
sar1

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
sar2 =np.vstack((lst1, lst3))
sar2

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [38]:
sar3 = np.hstack((lst3,lst4))
sar3

array([[9, 8, 7, 4],
       [6, 5, 4, 5]])

In [39]:
#  Joining 2D array using hstack() and vstack()
Arr1 = np.array([[0,1,2],
               [3,4,5],
               [6,7,8]])
Arr2 = np.array([[10,11,12],
                [13,14,15],
                [16,17,18]])
Arr3 = np.vstack((Arr1, Arr2))


In [40]:
Arr3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [41]:
Arr4 = np.hstack((Arr1, Arr2))
Arr4

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15],
       [ 6,  7,  8, 16, 17, 18]])

In [42]:
# Combing existing arrays using concatenate()
jar1 = np.concatenate((Arr1,Arr2), axis = 0)
jar1


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [43]:
jar2 = np.concatenate((Arr1, Arr2), axis = 1)
jar2

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15],
       [ 6,  7,  8, 16, 17, 18]])

In [44]:
jar7 = np.concatenate((Arr1, Arr2), axis = None)
jar7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [45]:
# Obtaining the subsets of array 

In [47]:
# Splitting Numpy arrays  to get Contigious Subsets
ary = np.arange(24.0).reshape(4,6)
ary

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [48]:
np.hsplit(ary, 2)

[array([[ 0.,  1.,  2.],
        [ 6.,  7.,  8.],
        [12., 13., 14.],
        [18., 19., 20.]]),
 array([[ 3.,  4.,  5.],
        [ 9., 10., 11.],
        [15., 16., 17.],
        [21., 22., 23.]])]

In [49]:
np.hsplit(ary , 3)

[array([[ 0.,  1.],
        [ 6.,  7.],
        [12., 13.],
        [18., 19.]]),
 array([[ 2.,  3.],
        [ 8.,  9.],
        [14., 15.],
        [20., 21.]]),
 array([[ 4.,  5.],
        [10., 11.],
        [16., 17.],
        [22., 23.]])]

In [50]:
np.hsplit(ary, 4)

ValueError: array split does not result in an equal division

In [51]:
np.vsplit(ary, 2)

[array([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]]),
 array([[12., 13., 14., 15., 16., 17.],
        [18., 19., 20., 21., 22., 23.]])]

In [52]:
np.vsplit(ary, 3)

ValueError: array split does not result in an equal division

In [53]:
ar1 , ar2 = np.vsplit(ary, 2)

In [54]:
ar1

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]])

In [55]:
ar2

array([[12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [56]:
a1, a2 , a3 = np.hsplit(ary , 3)

In [57]:
a1

array([[ 0.,  1.],
       [ 6.,  7.],
       [12., 13.],
       [18., 19.]])

In [58]:
a2

array([[ 2.,  3.],
       [ 8.,  9.],
       [14., 15.],
       [20., 21.]])

In [59]:
a3

array([[ 4.,  5.],
       [10., 11.],
       [16., 17.],
       [22., 23.]])

In [60]:
# using split() function
ar1d = [10,11,12,13,14,15,16,17,18,19]
np.split(ar1d, [2,6])

[array([10, 11]), array([12, 13, 14, 15]), array([16, 17, 18, 19])]

In [61]:
np.split(ary , [1, 4])

[array([[0., 1., 2., 3., 4., 5.]]),
 array([[ 6.,  7.,  8.,  9., 10., 11.],
        [12., 13., 14., 15., 16., 17.],
        [18., 19., 20., 21., 22., 23.]]),
 array([], shape=(0, 6), dtype=float64)]

In [62]:
np.split(ary, [2,5], axis = 1)

[array([[ 0.,  1.],
        [ 6.,  7.],
        [12., 13.],
        [18., 19.]]),
 array([[ 2.,  3.,  4.],
        [ 8.,  9., 10.],
        [14., 15., 16.],
        [20., 21., 22.]]),
 array([[ 5.],
        [11.],
        [17.],
        [23.]])]

In [63]:
art1 , art2, art3 = np.split(ary, [2,5], axis = 1)

In [64]:
art1

array([[ 0.,  1.],
       [ 6.,  7.],
       [12., 13.],
       [18., 19.]])

In [65]:
art2

array([[ 2.,  3.,  4.],
       [ 8.,  9., 10.],
       [14., 15., 16.],
       [20., 21., 22.]])

In [66]:
art3

array([[ 5.],
       [11.],
       [17.],
       [23.]])

In [67]:
ar1, ar2, ar3 = np.split(ary, [1,4])

In [68]:
ar1

array([[0., 1., 2., 3., 4., 5.]])

In [69]:
ar2

array([[ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [70]:
ar3

array([], shape=(0, 6), dtype=float64)

In [71]:
# arithmetic Operations on 2D array
ary

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [72]:
ary + 1.5

array([[ 1.5,  2.5,  3.5,  4.5,  5.5,  6.5],
       [ 7.5,  8.5,  9.5, 10.5, 11.5, 12.5],
       [13.5, 14.5, 15.5, 16.5, 17.5, 18.5],
       [19.5, 20.5, 21.5, 22.5, 23.5, 24.5]])

In [73]:
new  = ary + 2.1

In [74]:
new

array([[ 2.1,  3.1,  4.1,  5.1,  6.1,  7.1],
       [ 8.1,  9.1, 10.1, 11.1, 12.1, 13.1],
       [14.1, 15.1, 16.1, 17.1, 18.1, 19.1],
       [20.1, 21.1, 22.1, 23.1, 24.1, 25.1]])

In [75]:
ary + new

array([[ 2.1,  4.1,  6.1,  8.1, 10.1, 12.1],
       [14.1, 16.1, 18.1, 20.1, 22.1, 24.1],
       [26.1, 28.1, 30.1, 32.1, 34.1, 36.1],
       [38.1, 40.1, 42.1, 44.1, 46.1, 48.1]])